#!/bin/sh
#husky 0.14.3

execution_dir=$PWD

cd "$hooks_dir"
slackWebhook=`cat ../slackWebHook.conf`


cd "$execution_dir"
repoHost="https://github.com/"
repoUrl=`git config --get remote.origin.url`
repoBase=${repoUrl#"$repoHost"}

lastCommitMsg=`git log -1 --pretty=%B`

branchName=`git rev-parse --abbrev-ref HEAD`
curl -s -X POST -H 'Content-type: application/json' --data '{"text":"`'$repoBase' \t Commit \t '$branchName' \t '$lastCommitMsg'`"}' $slackWebhook >/dev/null 2>&1
